name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TRAMVAI_LINTERS_PAT }}
        fetch-depth: 0

    - name: Git Identity
      run: |
        git config --global user.name 'tramvaijsorg'
        git config --global user.email 'tramvaijsorg@users.noreply.github.com'

    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Clean install
      run: npm ci

    - name: Create release commit and tag
      run: |
        npm run version -- --no-push

    - name: Push release commit and tag
      run: git push --follow-tags

    - name: Publish packages
      run: npm run publish:ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
